# Generated by Django 4.0.5 on 2022-06-25 11:07

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=150)),
                ('closing_date', models.DateTimeField()),
                ('dhref', models.CharField(max_length=15)),
                ('ref', models.CharField(blank=True, max_length=150)),
                ('job_details', ckeditor.fields.RichTextField()),
                ('active_listing', models.BooleanField(default=False)),
                ('candidate_hired', models.BooleanField(default=False)),
                ('dhcomm_earned', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Job Listings',
                'ordering': ['-date_created'],
            },
        ),
    ]
