# Generated by Django 4.0.1 on 2022-06-25 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dhclients', '0002_rename_post_code_dhclient_postal_code'),
        ('careers', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='applicants',
            field=models.ManyToManyField(blank=True, related_name='applicants', to='dhclients.DHClient'),
        ),
    ]
