# Generated by Django 4.0.1 on 2022-06-25 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dhclients', '0002_rename_post_code_dhclient_postal_code'),
        ('careers', '0003_alter_job_applicants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='hired_candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_job_successes', to='dhclients.dhclient'),
        ),
    ]
