# Generated by Django 4.0.1 on 2022-07-02 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dhclients', '0007_alter_clientdocument_client'),
        ('careers', '0004_alter_job_hired_candidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_location',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dhclient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dhclient_applications', to='dhclients.dhclient')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to='careers.job')),
            ],
        ),
    ]
