# Generated by Django 4.0.1 on 2022-07-04 05:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0005_job_job_location_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='ApplicationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_docs', models.FileField(upload_to='Job_Application_Documents/')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('job_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_documents', to='careers.jobapplication')),
            ],
            options={
                'verbose_name_plural': 'Application Documents',
            },
        ),
    ]
