# Generated by Django 4.0.1 on 2022-07-04 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0006_jobapplication_date_created_applicationdocument'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicationdocument',
            old_name='application_docs',
            new_name='application_doc',
        ),
    ]
