# Generated by Django 4.0.1 on 2022-10-18 14:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dhclients', '0015_alter_employmenthistory_duties'),
        ('companies', '0004_company_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver_Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('req_id', models.CharField(max_length=25)),
                ('employment_type', models.SmallIntegerField(choices=[(1, 'Full-Time Employment'), (2, 'Part-Time Employment'), (3, 'Once-Off hire'), (4, 'Internship'), (5, 'Learnership')], default=1)),
                ('access_granted', models.BooleanField(default=False)),
                ('closed', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_requests', to='companies.company')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_requests', to='dhclients.dhclient')),
            ],
            options={
                'verbose_name_plural': 'Driver Requests',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='RequestStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(1, 'Recruitment process initiated'), (2, 'Driver informed and accepted'), (3, 'Driver informed and rejected'), (4, 'Recruitment process initiated'), (5, 'All necessary checks done (i.e. criminal, medical, etc)'), (6, 'Driver employed'), (7, 'Other')])),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('driver_req', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_statuses', to='driver_requests.driver_request')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
