# Generated by Django 4.0.1 on 2022-10-20 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver_requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requeststatus',
            name='note',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
