# Generated by Django 4.0.1 on 2022-10-26 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver_requests', '0002_requeststatus_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requeststatus',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Recruitment process initiated'), (2, 'Driver informed and accepted'), (3, 'Driver informed and rejected'), (4, 'Recruitment process initiated'), (5, 'All necessary checks done (i.e. criminal, medical, etc)'), (6, 'Driver employed'), (7, 'Other'), (8, 'Request Accepted'), (9, 'Request Rejected')]),
        ),
    ]
