# Generated by Django 4.0.5 on 2022-06-25 11:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=150)),
                ('company_reg_num', models.CharField(blank=True, max_length=30)),
                ('vat_num', models.CharField(blank=True, max_length=30)),
                ('contact_person', models.CharField(max_length=80)),
                ('contact_num1', models.CharField(max_length=20)),
                ('contact_num2', models.CharField(blank=True, max_length=20)),
                ('email_address', models.EmailField(blank=True, max_length=100)),
                ('address', models.CharField(max_length=500)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='countries.country')),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='CompanyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=250)),
                ('document', models.FileField(upload_to='Company_Documents/')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_documents', to='companies.company')),
            ],
            options={
                'verbose_name_plural': 'Company Documents',
            },
        ),
    ]
