# Generated by Django 4.0.1 on 2022-06-25 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_admins_company_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='user',
        ),
    ]
