# Generated by Django 4.0.1 on 2022-10-26 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactformenquiry',
            old_name='name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='contactformenquiry',
            name='surname',
        ),
    ]
