# Generated by Django 4.0.1 on 2022-10-26 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0002_rename_name_contactformenquiry_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactformenquiry',
            name='message',
            field=models.CharField(max_length=1000),
        ),
    ]
