# Generated by Django 4.0.5 on 2022-06-25 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dhclients', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dhclient',
            old_name='post_code',
            new_name='postal_code',
        ),
    ]
