# Generated by Django 4.0.1 on 2022-06-26 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dhclients', '0002_rename_post_code_dhclient_postal_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='dhclient',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='Profile_Pics/'),
        ),
    ]
