# Generated by Django 4.0.1 on 2022-06-26 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dhclients', '0003_dhclient_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='Driver_Documents/')),
                ('doc_type', models.IntegerField(choices=[(1, 'CV'), (2, "Driver's Licence"), (3, 'PrDP / Medical Certificate'), (4, 'ID Document'), (5, 'Passport'), (6, 'Other')], null=True)),
                ('doc_visibility', models.IntegerField(choices=[(1, 'Make Public'), (2, 'Make Private')], default=1, null=True)),
                ('other_type', models.CharField(blank=True, max_length=60, null=True)),
                ('doc_name', models.CharField(max_length=300, null=True)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Driver Documents',
            },
        ),
    ]
