# Generated by Django 4.0.1 on 2022-06-26 17:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dhclients', '0004_driverdocument'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DriverDocument',
            new_name='ClientDocument',
        ),
    ]
