# Generated by Django 4.0.1 on 2022-06-26 17:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dhclients', '0005_rename_driverdocument_clientdocument'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientdocument',
            options={'verbose_name_plural': 'Client Documents'},
        ),
        migrations.RemoveField(
            model_name='clientdocument',
            name='driver',
        ),
        migrations.AddField(
            model_name='clientdocument',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clientdocument',
            name='document',
            field=models.FileField(upload_to='Client_Documents/'),
        ),
    ]
