# Generated by Django 4.0.1 on 2022-08-27 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dhclients', '0010_dhclient_crossborder'),
    ]

    operations = [
        migrations.AddField(
            model_name='dhclient',
            name='location_id',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
