# Generated by Django 4.0.1 on 2022-08-28 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dhclients', '0013_dhclient_administrative_area_level_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dhclient',
            name='postal_code',
        ),
    ]
