# Generated by Django 4.0.1 on 2022-08-29 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dhclients', '0014_remove_dhclient_postal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employmenthistory',
            name='duties',
            field=models.CharField(max_length=2000),
        ),
    ]
