# Generated by Django 4.0.1 on 2022-06-26 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_courses', '0002_alter_code14course_price_alter_trainingcourse_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code14course',
            name='duration',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='trainingcourse',
            name='duration',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
