# Generated by Django 4.0.1 on 2022-07-14 15:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dhclients', '0010_dhclient_crossborder'),
        ('training_courses', '0003_alter_code14course_duration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course_Enrollees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=1000)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('enrollees', models.ManyToManyField(blank=True, through='training_courses.Course_Enrollees', to='dhclients.DHClient')),
                ('training_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_events', to='training_courses.trainingcourse')),
            ],
        ),
        migrations.AddField(
            model_name='course_enrollees',
            name='course_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training_courses.trainingevent'),
        ),
        migrations.AddField(
            model_name='course_enrollees',
            name='enrollee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dhclients.dhclient'),
        ),
    ]
