# Generated by Django 4.0.1 on 2022-07-28 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_courses', '0005_trainingdays_remove_trainingevent_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingevent',
            name='slots',
            field=models.ManyToManyField(to='training_courses.TrainingDays'),
        ),
    ]
