# Generated by Django 4.0.1 on 2022-08-08 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('training_courses', '0006_trainingevent_slots'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(max_length=20, unique=True)),
                ('paid', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('client', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_training_bookings', to=settings.AUTH_USER_MODEL)),
                ('training_event', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_event_bookings', to='training_courses.trainingevent')),
            ],
        ),
    ]
