# Generated by Django 4.0.1 on 2022-08-09 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_courses', '0007_trainingbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingevent',
            name='enrollees_num',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='trainingevent',
            name='fully_booked',
            field=models.BooleanField(default=False),
        ),
    ]
