# Generated by Django 4.0.1 on 2022-08-09 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training_courses', '0008_trainingevent_enrollees_num_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_slot', models.TimeField()),
            ],
        ),
        migrations.AddField(
            model_name='trainingbooking',
            name='stime',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_times', to='training_courses.trainingtime'),
        ),
        migrations.AddField(
            model_name='trainingdays',
            name='time_slots',
            field=models.ManyToManyField(blank=True, to='training_courses.TrainingTime'),
        ),
    ]
