# Generated by Django 4.0.1 on 2022-08-11 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training_courses', '0009_trainingtime_trainingbooking_stime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingdays',
            name='time_slots',
        ),
        migrations.RemoveField(
            model_name='trainingevent',
            name='slots',
        ),
        migrations.AddField(
            model_name='trainingdays',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_event_dates', to='training_courses.trainingevent'),
        ),
        migrations.AddField(
            model_name='trainingtime',
            name='date',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_date_times', to='training_courses.trainingevent'),
        ),
    ]
