# Generated by Django 4.0.1 on 2022-08-15 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training_courses', '0010_remove_trainingdays_time_slots_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingtime',
            name='date',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_date_times', to='training_courses.trainingdays'),
        ),
    ]
