# Generated by Django 4.0.1 on 2022-08-22 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_courses', '0011_alter_trainingtime_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingevent',
            name='hourly_training',
            field=models.BooleanField(default=False),
        ),
    ]
