# Generated by Django 4.0.1 on 2022-08-30 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_courses', '0014_remove_trainingevent_hourly_training'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingdays',
            name='training_slot',
            field=models.DateField(),
        ),
    ]
