# Generated by Django 4.0.1 on 2022-08-31 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_courses', '0015_alter_trainingdays_training_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingdays',
            name='training_slot',
            field=models.DateTimeField(),
        ),
    ]
