# Generated by Django 4.0.1 on 2022-09-30 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_courses', '0017_trainingcourse_elearning'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElearningEnquiries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('contact_num', models.CharField(max_length=25)),
                ('message', models.CharField(max_length=500)),
            ],
        ),
    ]
