# Generated by Django 4.0.1 on 2022-09-30 14:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('training_courses', '0018_elearningenquiries'),
    ]

    operations = [
        migrations.AddField(
            model_name='elearningenquiries',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
