# Generated by Django 4.0.1 on 2022-10-06 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_courses', '0022_trainingcourse_thirdparty_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingdays',
            name='training_slot',
            field=models.DateField(),
        ),
    ]
