# Generated by Django 4.0.1 on 2022-10-09 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training_courses', '0023_alter_trainingdays_training_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingbooking',
            name='tdate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='date_bookings', to='training_courses.trainingdays'),
        ),
    ]
