# Generated by Django 4.0.1 on 2022-10-09 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training_courses', '0024_trainingbooking_tdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingevent',
            name='enrollees',
        ),
    ]
