# Generated by Django 4.0.1 on 2022-10-09 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_courses', '0026_bookingtransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingtransaction',
            name='trans_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
