# Generated by Django 4.0.1 on 2022-10-27 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_courses', '0029_alter_trainingtime_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainingcourse',
            old_name='elearning',
            new_name='code14_course',
        ),
        migrations.RenameField(
            model_name='trainingcourse',
            old_name='thirdparty_course',
            new_name='elearning_course',
        ),
        migrations.AddField(
            model_name='trainingcourse',
            name='hourly_driving_course',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trainingcourse',
            name='hourly_simulator_course',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trainingcourse',
            name='multiday_course',
            field=models.BooleanField(default=False),
        ),
    ]
