# Generated by Django 4.0.1 on 2022-10-28 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_courses', '0030_rename_elearning_trainingcourse_code14_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingcourse',
            name='course_intro',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
