# Generated by Django 4.0.1 on 2022-11-03 07:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('training_courses', '0031_trainingcourse_course_intro'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectedCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollees_num', models.IntegerField(blank=True)),
                ('comment', models.CharField(blank=True, max_length=1000)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='trainingdays',
            name='event',
        ),
        migrations.RemoveField(
            model_name='trainingevent',
            name='training_course',
        ),
        migrations.AlterField(
            model_name='trainingdays',
            name='training_slot',
            field=models.DateTimeField(),
        ),
        migrations.AddField(
            model_name='trainingevent',
            name='training_courses',
            field=models.ManyToManyField(to='training_courses.SelectedCourse'),
        ),
    ]
