# Generated by Django 4.0.1 on 2022-11-03 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training_courses', '0032_selectedcourse_remove_trainingdays_event_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingevent',
            name='training_courses',
        ),
        migrations.DeleteModel(
            name='SelectedCourse',
        ),
    ]
