# Generated by Django 4.0.1 on 2022-11-03 08:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('training_courses', '0033_remove_trainingevent_training_courses_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectedCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollees_num', models.IntegerField(blank=True)),
                ('comment', models.CharField(blank=True, max_length=1000)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
