# Generated by Django 4.0.1 on 2022-11-03 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_courses', '0034_selectedcourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectedcourse',
            name='hourly_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
