# Generated by Django 4.0.1 on 2022-11-03 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training_courses', '0035_selectedcourse_hourly_limit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course_Enrollees',
        ),
    ]
