# Generated by Django 4.0.1 on 2022-11-03 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training_courses', '0037_selectedcourse_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingdays',
            name='selcourse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_dates', to='training_courses.selectedcourse'),
        ),
    ]
