# Generated by Django 4.0.1 on 2022-11-03 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training_courses', '0039_selectedcourse_trcourse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selectedcourse',
            name='event',
        ),
    ]
