# Generated by Django 4.0.1 on 2022-11-03 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training_courses', '0040_remove_selectedcourse_event'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SelectedCourse',
            new_name='Training',
        ),
    ]
