# Generated by Django 4.0.1 on 2022-11-04 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_courses', '0041_rename_selectedcourse_training'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='comment',
            field=models.CharField(max_length=1000),
        ),
    ]
