# Generated by Django 4.0.1 on 2022-11-05 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_courses', '0042_alter_training_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingcourse',
            name='hourly_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
