# Generated by Django 4.0.1 on 2022-11-08 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_courses', '0043_trainingcourse_hourly_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='enrollees_num',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
